services:
  app:
    image: node:24
    container_name: coffee_qr_app
    working_dir: /src/app
    command: sh -c "npm install && npx prisma db push && npm run seed && npm run dev"
    volumes:
      - ./:/src/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://root:root@db:3306/qrcode}
      NEXT_PUBLIC_AUTH_TOKEN: ${NEXT_PUBLIC_AUTH_TOKEN}
      API_AUTH_TOKEN_SECRET: ${API_AUTH_TOKEN_SECRET}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: mysql:8.1
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qrcode
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
  node_modules:
